default: &default
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 50
  timeout: 5000

development:
  <<: *default
  database: ping45_development

test:
  <<: *default
  database: ping45_test
